export { default as Dashboard } from './Home/Home';
export { default as NotesBoard } from './Notes/NotesBoard';
export { default as StatusView } from './Status/StatusView';
export { default as SchoolView } from './School/SchoolView';
export { default as ChoresView } from './Chores/ChoresView';
export { default as SmartHomeView } from './SmartHome/SmartHomeView';
export { default as RewardBoard } from './Rewards/RewardBoard';
export { default as SonosView } from './Sonos/SonosView';
export { default as AdminSettings } from './Admin/AdminSettings';
